# Generated by Django 5.2.3 on 2025-07-16 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('idade', models.PositiveIntegerField()),
                ('faixa', models.CharField(choices=[('branca', 'Branca'), ('cinza', 'Cinza'), ('azul', 'Azul'), ('amarela', 'Amarela'), ('laranja', 'Laranja'), ('verde', 'Verde'), ('roxa', 'Roxa'), ('marrom', 'Marrom'), ('preta', 'Preta')], max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
