# Generated by Django 5.2.5 on 2025-09-25 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Perfil do Usuário', 'verbose_name_plural': 'Perfis dos Usuários'},
        ),
        migrations.AddField(
            model_name='profile',
            name='conta_premium',
            field=models.BooleanField(default=False, verbose_name='Conta Premium'),
        ),
        migrations.AddField(
            model_name='profile',
            name='data_vencimento_premium',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de vencimento Premium'),
        ),
        migrations.AddField(
            model_name='profile',
            name='nivel',
            field=models.PositiveIntegerField(default=1, verbose_name='Nível'),
        ),
        migrations.AddField(
            model_name='profile',
            name='notificacoes_ativadas',
            field=models.BooleanField(default=True, verbose_name='Notificações ativadas'),
        ),
        migrations.AddField(
            model_name='profile',
            name='pontos_experiencia',
            field=models.PositiveIntegerField(default=0, verbose_name='Pontos de experiência'),
        ),
        migrations.AddField(
            model_name='profile',
            name='tema_preferido',
            field=models.CharField(choices=[('claro', 'Claro'), ('escuro', 'Escuro')], default='claro', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='faixa',
            field=models.CharField(choices=[('branca', 'Branca'), ('cinza', 'Cinza'), ('azul', 'Azul'), ('amarela', 'Amarela'), ('laranja', 'Laranja'), ('verde', 'Verde'), ('roxa', 'Roxa'), ('marrom', 'Marrom'), ('preta', 'Preta')], default='branca', max_length=10, verbose_name='Faixa atual'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='idade',
            field=models.PositiveIntegerField(verbose_name='Idade'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nome',
            field=models.CharField(max_length=150, verbose_name='Nome completo'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='HistoricoFaixas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faixa_anterior', models.CharField(max_length=10, verbose_name='Faixa anterior')),
                ('faixa_atual', models.CharField(max_length=10, verbose_name='Faixa atual')),
                ('data_mudanca', models.DateTimeField(auto_now_add=True, verbose_name='Data da mudança')),
                ('motivo', models.TextField(blank=True, null=True, verbose_name='Motivo da mudança')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_faixas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Faixas',
                'verbose_name_plural': 'Históricos de Faixas',
                'ordering': ['-data_mudanca'],
            },
        ),
    ]
