# Generated by Django 5.2.5 on 2025-10-09 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_profile_options_profile_conta_premium_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoRecuperacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email do usuário')),
                ('codigo', models.CharField(max_length=6, verbose_name='Código de 6 dígitos')),
                ('usado', models.BooleanField(default=False, verbose_name='Código já foi usado')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('data_expiracao', models.DateTimeField(verbose_name='Data de expiração')),
            ],
            options={
                'verbose_name': 'Código de Recuperação',
                'verbose_name_plural': 'Códigos de Recuperação',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
