# Generated by Django 5.2.5 on 2025-10-17 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pag6', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='progressoelemento',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Chave da Sessão'),
        ),
        migrations.AlterField(
            model_name='progressoelemento',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progresso_elementos_pag6', to=settings.AUTH_USER_MODEL),
        ),
    ]
