# Generated by Django 5.2.5 on 2025-10-17 15:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pag6', '0002_progressoelemento_session_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='progressoelemento',
            unique_together={('session_key', 'pagina', 'elemento_id'), ('usuario', 'pagina', 'elemento_id')},
        ),
    ]
