# Generated by Django 5.2.5 on 2025-09-29 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressoQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dificuldade', models.CharField(max_length=20, verbose_name='Dificuldade')),
                ('pergunta_atual', models.PositiveIntegerField(default=0, verbose_name='Pergunta Atual')),
                ('total_perguntas', models.PositiveIntegerField(default=0, verbose_name='Total de Perguntas')),
                ('acertos', models.PositiveIntegerField(default=0, verbose_name='Acertos')),
                ('erros', models.PositiveIntegerField(default=0, verbose_name='Erros')),
                ('pontuacao', models.PositiveIntegerField(default=0, verbose_name='Pontuação')),
                ('quiz_completo', models.BooleanField(default=False, verbose_name='Quiz Completo')),
                ('data_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Data de Início')),
                ('data_fim', models.DateTimeField(blank=True, null=True, verbose_name='Data de Fim')),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresso_quiz', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progresso do Quiz',
                'verbose_name_plural': 'Progressos do Quiz',
                'ordering': ['-data_atualizacao'],
                'unique_together': {('usuario', 'dificuldade', 'data_inicio')},
            },
        ),
    ]
