# Generated by Django 5.2.5 on 2025-09-29 20:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_progressoquiz'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progressoquiz',
            options={'ordering': ['usuario', 'dificuldade'], 'verbose_name': 'Progresso do Quiz', 'verbose_name_plural': 'Progressos do Quiz'},
        ),
        migrations.AlterUniqueTogether(
            name='progressoquiz',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='progressoquiz',
            name='nivel_desbloqueado',
            field=models.BooleanField(default=False, verbose_name='Nível Desbloqueado'),
        ),
        migrations.AlterField(
            model_name='progressoquiz',
            name='dificuldade',
            field=models.CharField(choices=[('easy', 'Fácil'), ('medium', 'Médio'), ('hard', 'Difícil'), ('expert', 'Expert')], max_length=20, verbose_name='Dificuldade'),
        ),
        migrations.AlterUniqueTogether(
            name='progressoquiz',
            unique_together={('usuario', 'dificuldade')},
        ),
    ]
