# Generated by Django 5.2.5 on 2025-10-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_progressoquiz_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progressoquiz',
            name='nivel_desbloqueado',
        ),
        migrations.AddField(
            model_name='progressoquiz',
            name='progresso_percentual',
            field=models.FloatField(default=0.0, verbose_name='Progresso Percentual'),
        ),
        migrations.AlterField(
            model_name='progressoquiz',
            name='total_perguntas',
            field=models.PositiveIntegerField(default=15, verbose_name='Total de Perguntas'),
        ),
    ]
