# Generated by Django 5.2.5 on 2026-03-14 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_remove_progressoquiz_nivel_desbloqueado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='progressousuario',
            name='categoria_titulo',
            field=models.CharField(default='Kohai', max_length=50, verbose_name='Título/Categoria no ranking'),
        ),
        migrations.AddField(
            model_name='progressousuario',
            name='nivel_quiz',
            field=models.PositiveIntegerField(default=1, verbose_name='Nível atual do quiz'),
        ),
        migrations.CreateModel(
            name='QuizRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40, null=True, verbose_name='Chave da sessão (anônimo)')),
                ('nickname', models.CharField(max_length=100, verbose_name='Nome/Apelido no ranking')),
                ('cidade', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('xp_total', models.PositiveIntegerField(default=0, verbose_name='XP total')),
                ('nivel_quiz', models.PositiveIntegerField(default=1, verbose_name='Nível do quiz')),
                ('categoria_titulo', models.CharField(default='Kohai', max_length=50, verbose_name='Categoria (Kohai, Ninja, Samurai, ..., Jigoro Kano)')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última atualização')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_ranking', to=settings.AUTH_USER_MODEL, verbose_name='Usuário (se logado)')),
            ],
            options={
                'verbose_name': 'Entrada no Ranking do Quiz',
                'verbose_name_plural': 'Ranking do Quiz',
                'ordering': ['-xp_total'],
            },
        ),
    ]
