# Generated by Django 5.2.5 on 2026-03-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_quiz_ranking_e_progresso_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizranking',
            name='dojo',
            field=models.CharField(blank=True, max_length=150, verbose_name='Dojo onde treina'),
        ),
    ]
