# Generated by Django 5.2.5 on 2025-09-25 15:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(verbose_name='Access Token')),
                ('public_key', models.CharField(max_length=200, verbose_name='Public Key')),
                ('webhook_url', models.URLField(verbose_name='URL do Webhook')),
                ('webhook_secret', models.CharField(max_length=200, verbose_name='Secret do Webhook')),
                ('ambiente', models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Produção')], default='sandbox', max_length=10)),
                ('ativo', models.BooleanField(default=True, verbose_name='Configuração ativa')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de Pagamento',
                'verbose_name_plural': 'Configurações de Pagamento',
            },
        ),
        migrations.CreateModel(
            name='PlanoPremium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do plano')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('duracao_dias', models.PositiveIntegerField(verbose_name='Duração em dias')),
                ('ativo', models.BooleanField(default=True, verbose_name='Plano ativo')),
                ('acesso_ilimitado_quiz', models.BooleanField(default=True, verbose_name='Acesso ilimitado ao quiz')),
                ('relatorios_detalhados', models.BooleanField(default=True, verbose_name='Relatórios detalhados')),
                ('suporte_prioritario', models.BooleanField(default=False, verbose_name='Suporte prioritário')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plano Premium',
                'verbose_name_plural': 'Planos Premium',
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('payment', 'Pagamento'), ('subscription', 'Assinatura'), ('invoice', 'Fatura'), ('point_integration_wh', 'Ponto de Integração')], max_length=50, verbose_name='Tipo de evento')),
                ('action', models.CharField(max_length=50, verbose_name='Ação')),
                ('id_mercadopago', models.CharField(max_length=100, verbose_name='ID Mercado Pago')),
                ('external_reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Referência externa')),
                ('data_recebida', models.JSONField(verbose_name='Dados recebidos')),
                ('processado', models.BooleanField(default=False, verbose_name='Processado')),
                ('erro_processamento', models.TextField(blank=True, null=True, verbose_name='Erro no processamento')),
                ('data_recebimento', models.DateTimeField(auto_now_add=True, verbose_name='Data de recebimento')),
                ('data_processamento', models.DateTimeField(blank=True, null=True, verbose_name='Data de processamento')),
            ],
            options={
                'verbose_name': 'Evento Webhook',
                'verbose_name_plural': 'Eventos Webhook',
                'ordering': ['-data_recebimento'],
            },
        ),
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('cancelada', 'Cancelada'), ('expirada', 'Expirada'), ('suspensa', 'Suspensa')], default='ativa', max_length=20)),
                ('data_inicio', models.DateTimeField(verbose_name='Data de início')),
                ('data_vencimento', models.DateTimeField(verbose_name='Data de vencimento')),
                ('data_cancelamento', models.DateTimeField(blank=True, null=True, verbose_name='Data de cancelamento')),
                ('subscription_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID da Assinatura MP')),
                ('external_reference', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Referência externa')),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas', to=settings.AUTH_USER_MODEL)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.planopremium')),
            ],
            options={
                'verbose_name': 'Assinatura',
                'verbose_name_plural': 'Assinaturas',
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('cancelled', 'Cancelado'), ('refunded', 'Reembolsado')], default='pending', max_length=20)),
                ('tipo', models.CharField(choices=[('assinatura', 'Assinatura'), ('compra_avulsa', 'Compra Avulsa')], default='assinatura', max_length=20)),
                ('payment_id', models.CharField(max_length=100, unique=True, verbose_name='ID do Pagamento MP')),
                ('external_reference', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Referência externa')),
                ('descricao', models.TextField(verbose_name='Descrição do pagamento')),
                ('metodo_pagamento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Método de pagamento')),
                ('data_pagamento', models.DateTimeField(blank=True, null=True, verbose_name='Data do pagamento')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('assinatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.assinatura')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
