# Generated by Django 5.2.5 on 2025-09-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracaopagamento',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='configuracaopagamento',
            name='public_key',
        ),
        migrations.RemoveField(
            model_name='configuracaopagamento',
            name='webhook_secret',
        ),
        migrations.RemoveField(
            model_name='webhookevent',
            name='data_recebida',
        ),
        migrations.RemoveField(
            model_name='webhookevent',
            name='external_reference',
        ),
        migrations.RemoveField(
            model_name='webhookevent',
            name='id_mercadopago',
        ),
        migrations.AddField(
            model_name='configuracaopagamento',
            name='access_token_encrypted',
            field=models.TextField(default='', verbose_name='Access Token (Criptografado)'),
        ),
        migrations.AddField(
            model_name='configuracaopagamento',
            name='last_used',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último uso'),
        ),
        migrations.AddField(
            model_name='configuracaopagamento',
            name='public_key_encrypted',
            field=models.TextField(default='', verbose_name='Public Key (Criptografado)'),
        ),
        migrations.AddField(
            model_name='configuracaopagamento',
            name='usage_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Contador de uso'),
        ),
        migrations.AddField(
            model_name='configuracaopagamento',
            name='webhook_secret_encrypted',
            field=models.TextField(default='', verbose_name='Secret do Webhook (Criptografado)'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='card_holder_name_encrypted',
            field=models.TextField(blank=True, null=True, verbose_name='Nome no cartão (Criptografado)'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='card_last_four_encrypted',
            field=models.TextField(blank=True, null=True, verbose_name='Últimos 4 dígitos (Criptografado)'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP do pagamento'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='payer_document_encrypted',
            field=models.TextField(blank=True, null=True, verbose_name='CPF/Documento (Criptografado)'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='payer_email_encrypted',
            field=models.TextField(blank=True, null=True, verbose_name='Email do pagador (Criptografado)'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='payer_name_encrypted',
            field=models.TextField(blank=True, null=True, verbose_name='Nome do pagador (Criptografado)'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='payer_phone_encrypted',
            field=models.TextField(blank=True, null=True, verbose_name='Telefone (Criptografado)'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='user_agent',
            field=models.TextField(blank=True, null=True, verbose_name='User Agent'),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='data_recebida_encrypted',
            field=models.TextField(default='', verbose_name='Dados recebidos (Criptografados)'),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='external_reference_encrypted',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Referência externa (Criptografada)'),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='id_mercadopago_encrypted',
            field=models.TextField(default='', verbose_name='ID Mercado Pago (Criptografado)'),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP do webhook'),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='signature',
            field=models.TextField(blank=True, null=True, verbose_name='Assinatura do webhook'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='payment_id',
            field=models.CharField(max_length=200, unique=True, verbose_name='ID do Pagamento MP (Criptografado)'),
        ),
    ]
