# Generated by Django 5.2.5 on 2025-09-25 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_configuracaopagamento_access_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reembolso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do reembolso')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('processado', 'Processado'), ('falhou', 'Falhou'), ('cancelado', 'Cancelado')], default='pendente', max_length=20, verbose_name='Status')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da solicitação')),
                ('data_reembolso', models.DateTimeField(blank=True, null=True, verbose_name='Data do reembolso')),
                ('motivo', models.TextField(blank=True, null=True, verbose_name='Motivo do reembolso')),
                ('_refund_id', models.TextField(blank=True, null=True, verbose_name='ID do reembolso')),
                ('_refund_data', models.TextField(blank=True, null=True, verbose_name='Dados do reembolso')),
                ('assinatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reembolsos', to='payments.assinatura')),
            ],
            options={
                'verbose_name': 'Reembolso',
                'verbose_name_plural': 'Reembolsos',
                'ordering': ['-data_solicitacao'],
            },
        ),
    ]
