# Generated by Django 5.2.5 on 2025-10-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_reembolso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracaopagamento',
            name='access_token_encrypted',
        ),
        migrations.RemoveField(
            model_name='configuracaopagamento',
            name='public_key_encrypted',
        ),
        migrations.RemoveField(
            model_name='configuracaopagamento',
            name='webhook_secret_encrypted',
        ),
        migrations.AddField(
            model_name='configuracaopagamento',
            name='access_token',
            field=models.TextField(default='', verbose_name='Access Token'),
        ),
        migrations.AddField(
            model_name='configuracaopagamento',
            name='public_key',
            field=models.TextField(default='', verbose_name='Public Key'),
        ),
        migrations.AddField(
            model_name='configuracaopagamento',
            name='webhook_secret',
            field=models.TextField(default='', verbose_name='Secret do Webhook'),
        ),
    ]
