# Generated by Django 5.2.5 on 2025-10-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_remove_configuracaopagamento_access_token_encrypted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagamento',
            name='card_holder_name_encrypted',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='card_last_four_encrypted',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='payer_document_encrypted',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='payer_email_encrypted',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='payer_name_encrypted',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='payer_phone_encrypted',
        ),
        migrations.RemoveField(
            model_name='webhookevent',
            name='data_recebida_encrypted',
        ),
        migrations.RemoveField(
            model_name='webhookevent',
            name='external_reference_encrypted',
        ),
        migrations.RemoveField(
            model_name='webhookevent',
            name='id_mercadopago_encrypted',
        ),
        migrations.AddField(
            model_name='pagamento',
            name='card_holder_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome no cartão'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='card_last_four',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Últimos 4 dígitos'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='payer_document',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CPF/Documento'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='payer_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email do pagador'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='payer_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do pagador'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='payer_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='data_recebida',
            field=models.JSONField(default=dict, verbose_name='Dados recebidos'),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='external_reference',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Referência externa'),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='id_mercadopago',
            field=models.CharField(default='', max_length=100, verbose_name='ID Mercado Pago'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='payment_id',
            field=models.CharField(max_length=200, unique=True, verbose_name='ID do Pagamento MP'),
        ),
    ]
