# Generated by Django 5.2.5 on 2025-10-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_remove_pagamento_card_holder_name_encrypted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planopremium',
            name='imagem_historia',
            field=models.ImageField(blank=True, null=True, upload_to='planos/imagens/', verbose_name='Imagem da História'),
        ),
        migrations.AddField(
            model_name='planopremium',
            name='imagem_palavras',
            field=models.ImageField(blank=True, null=True, upload_to='planos/imagens/', verbose_name='Imagem das Palavras'),
        ),
        migrations.AddField(
            model_name='planopremium',
            name='imagem_principal',
            field=models.ImageField(blank=True, null=True, upload_to='planos/imagens/', verbose_name='Imagem Principal'),
        ),
        migrations.AddField(
            model_name='planopremium',
            name='imagem_quiz',
            field=models.ImageField(blank=True, null=True, upload_to='planos/imagens/', verbose_name='Imagem do Quiz'),
        ),
        migrations.AddField(
            model_name='planopremium',
            name='imagem_relatorios',
            field=models.ImageField(blank=True, null=True, upload_to='planos/imagens/', verbose_name='Imagem dos Relatórios'),
        ),
        migrations.AddField(
            model_name='planopremium',
            name='imagem_tecnicas',
            field=models.ImageField(blank=True, null=True, upload_to='planos/imagens/', verbose_name='Imagem das Técnicas'),
        ),
    ]
