# Generated by Django 5.2.5 on 2025-10-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_planopremium_imagem_historia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planopremium',
            name='imagem_historia',
        ),
        migrations.RemoveField(
            model_name='planopremium',
            name='imagem_palavras',
        ),
        migrations.RemoveField(
            model_name='planopremium',
            name='imagem_principal',
        ),
        migrations.RemoveField(
            model_name='planopremium',
            name='imagem_quiz',
        ),
        migrations.RemoveField(
            model_name='planopremium',
            name='imagem_relatorios',
        ),
        migrations.RemoveField(
            model_name='planopremium',
            name='imagem_tecnicas',
        ),
        migrations.AddField(
            model_name='planopremium',
            name='imagem_1',
            field=models.ImageField(blank=True, null=True, upload_to='planos/imagens/', verbose_name='Imagem 1 - Conteúdo Principal'),
        ),
        migrations.AddField(
            model_name='planopremium',
            name='imagem_2',
            field=models.ImageField(blank=True, null=True, upload_to='planos/imagens/', verbose_name='Imagem 2 - Quiz e Relatórios'),
        ),
        migrations.AddField(
            model_name='planopremium',
            name='imagem_3',
            field=models.ImageField(blank=True, null=True, upload_to='planos/imagens/', verbose_name='Imagem 3 - Técnicas e História'),
        ),
    ]
