# Generated by Django 5.2.5 on 2025-10-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_remove_planopremium_imagem_historia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planopremium',
            name='imagem_1',
            field=models.ImageField(blank=True, null=True, upload_to='planos/imagens/', verbose_name='Imagem 1 - Quiz e Aprendizado'),
        ),
        migrations.AlterField(
            model_name='planopremium',
            name='imagem_2',
            field=models.ImageField(blank=True, null=True, upload_to='planos/imagens/', verbose_name='Imagem 2 - Vídeos de Técnicas'),
        ),
        migrations.AlterField(
            model_name='planopremium',
            name='imagem_3',
            field=models.ImageField(blank=True, null=True, upload_to='planos/imagens/', verbose_name='Imagem 3 - Organização e Estrutura'),
        ),
    ]
