# Generated by Django 5.2.5 on 2025-09-29 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressoElemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagina', models.CharField(max_length=50, verbose_name='Página')),
                ('elemento_id', models.CharField(max_length=100, verbose_name='ID do Elemento')),
                ('elemento_tipo', models.CharField(max_length=50, verbose_name='Tipo do Elemento')),
                ('aprendido', models.BooleanField(default=False, verbose_name='Aprendido')),
                ('data_aprendizado', models.DateTimeField(blank=True, null=True, verbose_name='Data do Aprendizado')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresso_elementos_pag3', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progresso de Elemento',
                'verbose_name_plural': 'Progressos de Elementos',
                'ordering': ['-data_atualizacao'],
                'unique_together': {('usuario', 'pagina', 'elemento_id')},
            },
        ),
    ]
